## From country to country

In [225]:
df_migr_tot.head(10)

          Origin          Destination  Year  value
462  Afghanistan          Afghanistan  1960    0.0
463  Afghanistan              Albania  1960    0.0
464  Afghanistan              Algeria  1960   41.0
465  Afghanistan       American Samoa  1960    0.0
466  Afghanistan              Andorra  1960    0.0
467  Afghanistan               Angola  1960    0.0
468  Afghanistan             Anguilla  1960    0.0
469  Afghanistan  Antigua and Barbuda  1960    0.0
470  Afghanistan            Argentina  1960    6.0
471  Afghanistan              Armenia  1960    0.0

In [66]:
average_flux = df_migr_tot.pivot_table(values='value',index='Origin',columns='Destination')
average_flux.head()

Destination,Afghanistan,Albania,Algeria,American Samoa,Andorra,Angola,Anguilla,Antigua and Barbuda,Argentina,Armenia,...,Vanuatu,"Venezuela, RB",Vietnam,Virgin Islands (U.S.),"Virgin Islands, British",Wallis and Futuna,West Bank and Gaza,"Yemen, Rep.",Zambia,Zimbabwe
Origin,,,,,,,,,,,,,,,,,,,,,
Afghanistan,0.0,0.0,17.6,0.0,2.6,0.0,0.0,0.0,9.8,1.4,...,1.8,7.4,3.8,0.0,0.0,0.0,64.6,2023.2,0.4,1.0
Albania,0.6,0.0,6.8,0.0,66.4,1.6,0.0,0.0,43.8,1.4,...,0.0,4.2,4.4,0.2,0.0,0.0,28.0,16.4,1.2,6.0
Algeria,28.2,0.0,0.0,0.0,110.0,4.2,0.0,4.4,67.2,0.0,...,0.0,38.8,9.2,13.0,2.6,0.0,5487.4,1792.4,56.0,689.0
American Samoa,0.2,0.0,0.0,0.0,0.0,0.0,0.0,1.8,0.0,0.0,...,3.8,0.2,0.0,0.6,0.0,0.0,0.0,4.2,0.0,0.0
Andorra,0.0,0.0,0.2,0.0,0.0,0.2,0.0,0.0,2.4,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4,0.0

In [67]:
df_migr_tot['Country']

KeyError: 'Country'

Include region

In [ ]:
countries = pd.read_csv('data/countries.csv')
countries = countries[['ShortName','Region']]
countries.columns = ['Country','Region']

In [ ]:
# create country-region mapping dataframe
country_region = pd.DataFrame(countries['Region'],index=countries['Country'])
# join it with indicator dataframe
data_set_cut = data_set_cut.join(country_region, on = 'Country')

In [ ]:
data_set_origin = data_set_cut.rename(columns = {'Country':'Origin'})
data_set_destination = data_set_cut.rename(columns = {'Country':'Destination'})

In [ ]:
df_migr_ind = pd.merge(df_migr_tot,data_set_origin,on=['Origin','Year'])
df_migr_ind = pd.merge(df_migr_ind,data_set_destination,on=['Destination','Year'])

In [ ]:
df_migr_ind.shape

Huge increase in datapoints.

In [ ]:
df_migr_ind.head()